### ISSUE TITLE
請問編譯成功後, 如何執行程式?

### ISSUE THREAD

**Issue by zadehalex** [PassByYou888/zAI#1]
請問 PassByYou888, 

這程式是編譯成功後就能執行嗎? 因為我編譯成功後, 少了下面類型的檔案與dll.
其次 AI.conf 中說要申請 key, 可是 http://zpascal.net 連過去後 是 iis 廣告的網站?

*.svm_od     
*.svm_od_marsha
*.svm_dnn_od
*.imgDataSet
zAI_cuda_x64.dll

face_alignment.exe, face_det_cpu.exe 加入人臉圖片後,沒有任何事發生,好像不會辨識.

**Comment by pony5551** [comment]
楼上加qq群490269542

**Comment by zadehalex** [comment]
謝謝! 新年快樂!

**Comment by PassByYou888** [comment]
作者手误,导致群号在半年时间段中都不可被查到和加入,非常不好意思.现在群号已经重新开放了

https://zpascal.net
有丰富的入门指南文档

你也可以直接通过加作者qq600585当面提问
